const PUBLIC_MESSAGES = {
  ALREADY_IN_WISHLIST: 'This game is already in your wishlist.',
  CLOUD_SAVES_DISABLED: 'Cloud saves are not available for this game.',
  CONFLICT: 'This action could not be completed.',
  CSRF_INIT_FAILED: 'Please refresh the page and try again.',
  CSRF_VALIDATION_FAILED: 'Please refresh the page and try again.',
  EMAIL_TAKEN: 'That email is already registered.',
  FORBIDDEN: 'You do not have permission to do that.',
  GAME_ACCESS_REQUIRED: 'This game is not available in your library.',
  GAME_ASSET_UNAVAILABLE: 'The download is not available right now.',
  GAME_NOT_FOUND: 'That game could not be found.',
  GAME_NOT_OWNED: 'This game is not available in your library.',
  GAME_RELEASE_NOT_CONFIGURED: 'The download is not available right now.',
  GAME_RELEASE_NOT_FOUND: 'The download is not available right now.',
  GITHUB_GAMES_ACCESS_DENIED: 'The download is not available right now.',
  GITHUB_GAMES_NOT_CONFIGURED: 'The download is not available right now.',
  GITHUB_REDIRECT_UNAVAILABLE: 'The download failed. Try again later.',
  GITHUB_UNAVAILABLE: 'The download failed. Try again later.',
  INTERNAL_ERROR: 'Something went wrong. Try again later.',
  INVALID_CREDENTIALS: 'Email or password is incorrect.',
  INVALID_JSON: 'The request could not be read.',
  INVALID_PASSWORD: 'Current password is incorrect.',
  INVALID_REQUEST: 'The request could not be completed.',
  INVALID_TOKEN: 'This link is invalid or has expired.',
  INVALID_TOTP: 'Invalid 2FA code.',
  ITCH_ACCOUNT_IN_USE: 'This itch.io account is already connected.',
  ITCH_GAME_NOT_CONFIGURED: 'This game is not ready yet.',
  ITCH_LIBRARY_INVALID: 'Your itch.io library could not be checked.',
  ITCH_LIBRARY_TOO_LARGE: 'Your itch.io library could not be checked.',
  ITCH_LINK_EXPIRED: 'This connection request expired. Start again.',
  ITCH_NOT_CONFIGURED: 'itch.io connection is temporarily unavailable.',
  ITCH_NOT_CONNECTED: 'Connect your itch.io account to continue.',
  ITCH_PROFILE_INVALID: 'The itch.io account could not be verified.',
  ITCH_RECONNECT_REQUIRED: 'Reconnect your itch.io account to continue.',
  ITCH_SCOPE_MISSING: 'Required itch.io access was not granted.',
  ITCH_UNAVAILABLE: 'itch.io is unavailable. Try again later.',
  NEWSLETTER_LINK_INVALID: 'This newsletter link is invalid or expired.',
  NOT_FOUND: 'This page or action could not be found.',
  NOT_IN_WISHLIST: 'Game not found in your wishlist.',
  PAYLOAD_TOO_LARGE: 'That file or request is too large.',
  PROFILE_NOT_FOUND: 'Profile not found.',
  PUSH_TOKEN_INVALID: 'Notifications could not be enabled.',
  RATE_LIMITED: 'Too many attempts. Try again shortly.',
  RECAPTCHA_FAILED: 'Please complete the security check.',
  RECAPTCHA_INVALID_RESPONSE: 'Please complete the security check.',
  RECAPTCHA_NOT_CONFIGURED: 'Security verification is temporarily unavailable.',
  RECAPTCHA_REQUIRED: 'Please complete the security check.',
  RECAPTCHA_UNAVAILABLE: 'Security verification is temporarily unavailable.',
  SAVE_CONFLICT: 'A newer cloud save is available.',
  SAVE_INVALID: 'The save file could not be read.',
  SAVE_NOT_FOUND: 'No cloud save was found.',
  SAVE_TOO_LARGE: 'This save is too large to sync.',
  SECRET_DECRYPT_FAILED: 'This account needs to reconnect a service.',
  SERVICE_UNAVAILABLE: 'Service unavailable. Try again later.',
  SESSION_NOT_ACTIVE: 'This play session is already closed.',
  SESSION_START_FAILED: 'The play session could not be started.',
  TELEMETRY_CONTEXT_INVALID: 'This action could not be verified.',
  TOTP_ALREADY_ENABLED: '2FA is already enabled.',
  TOTP_NOT_SETUP: '2FA is not set up.',
  TOTP_SETUP_FAILED: '2FA could not be prepared right now.',
  TRUSTED_ORIGIN_REQUIRED: 'Open the authenticated app and try again.',
  TWO_FACTOR_CHALLENGE_EXPIRED: 'Please sign in again.',
  UNAUTHENTICATED: 'Please sign in to continue.',
  USER_NOT_FOUND: 'Account not found.',
  USERNAME_TAKEN: 'That username is already taken.',
  VALIDATION_ERROR: 'Check the fields and try again.',
};

const STATUS_MESSAGES = {
  400: 'Check the fields and try again.',
  401: 'Please sign in to continue.',
  403: 'You do not have permission to do that.',
  404: 'This page or action could not be found.',
  409: 'This action could not be completed.',
  413: 'That file or request is too large.',
  429: 'Too many attempts. Try again shortly.',
  500: 'Something went wrong. Try again later.',
  502: 'Service unavailable. Try again later.',
  503: 'Service unavailable. Try again later.',
};

export function publicErrorMessage(code, status, fallback) {
  const normalizedCode = String(code || '').toUpperCase();
  if (PUBLIC_MESSAGES[normalizedCode]) return PUBLIC_MESSAGES[normalizedCode];
  if (STATUS_MESSAGES[status]) return STATUS_MESSAGES[status];
  return fallback || 'Something went wrong. Try again later.';
}
